<!DOCTYPE html>
<html>
<head><h1>Mohammad Revy Zanuar Nur Wahid</h1>
	<title></title>
</head>
<body>
	<h1><center><b>Sejarah Manchester United<b/></center></h1>
	<center><img src="file://C:/Program Files (x86)/xampp/htdocs/2.jpeg" width=200 height=200"></center>

	<br>United dipenuhi dengan sejarah kemenangan dan tragedi yang luar biasa, termasuk gaya permainan menyerang, permainan sepakbola yang menghibur, seringkali berakhir dengan akhir pertandingan yang dramatis layaknya film action.</br> 


	<br>Manchester UnitedFootball Club didirikan pada tahun 1878, namun dengan nama yang berbeda yaitu Newton Heath LYR (Lancashire and Yorkshire Railway). Pada awalnya tidak ada orang yang tahu sebesar apa klub itu akan berkembang. Memang ketika ajang Football League didirikan pada tahun 1888, klub Newton Heath tidak langsung bergabung di kompetisi tersebut. Mereka tidak yakin bahwa kualitas mereka cukup baik untuk bermain dan melawan klub seperti Blackburn Rovers dan Preston North End. Hingga akhirnya pada tahun 1902, mereka akhirnya bergabung di Division One. Sayangnya setelah hanya 2 musim bermain, mereka terdegradasi ke Division Two.</br>

	<br>Tidak hanya performa tim yang menjadi permasalahan mereka, masalah finansial juga mulai menggerogoti klub tersebut. Hingga akhirnya di awal abad ke-21 klub tersebut diprediksi akan segera bubar. Namun beruntung hal tersebut tidak terjadi karena pengusaha lokal pemilik usaha pembuatan bir, John Henry Davies bersedia untuk menyelamatkan klub tersebut. Menurut catatan sejarah, Davies mengetahui tentang keadaan buruk klub tersebut ketika ia menemukan anjing peliharaan kapten tim Harry Stafford.</br> 

	<br>Ia kemudian memutuskan untuk menginvestasikan dana di Newton Heath, dengan keuntungan berupa bunga investasi selama menjadi investor. Hal ini kemudian yang mendasari penggantian nama klub. Beberapa pilihan nama pada awalnya termasuk Manchester Central dan Manchester Celtic, namun akhirnya nama yang dipilih adalah Manchester United, dan diresmikan pada bulan April/Mei tahun 1902.</br> 

	<br>Sosok lain yang banyak memberikan pengaruh dalam perkembangan United adalah Ernest Mangnall, yang sebenarnya ditunjuk sebagai sekretaris pada bulan September 1903. Akan tetapi ia lebih dikenal sebagai manajer pertama yang pernah dimiliki klub tersebut. Pemain yang didatangkannya seperti penjaga gawang Harry Moger dan penyerang Charlie Sagar, menjadi pelengkap skuat yang tepat hingga tim tersebut berhasil menduduki peringkat ketiga di akhir musim 1903/04 dan musim 1904/05 di ajang Division Two.</br>

	<br>Kemudian kesuksesan mereka berlanjut di musim 1905/06, dimana musim tersebut adalah salah satu musim yang menunjukkan kehebatan Manchester United di masa-masa awal berdirinya klub tersebut. Pemain bertahan seperti Dick Duckworth, Alex Bell dan kapten tim Charlie Roberts adalah pemain-pemain kunci untuk keberhasilan tim tersebut dalam menembus babak perempat final di ajang Piala FA, dan juga pencapaian luar biasa lainnya yaitu menjadi runner-up di ajang Division Two.</br> 

	<br>12 tahun setelah terdegradasi, United akhirnya kembali mendapatkan promosi ke liga tertinggi di Inggris, Division One. Sebagai perayaan, Mangnall mendatangkan Billy Meredith dari klub rival mereka, Manchester City. Dijuluki Welsh Wizard, Meredith dikabarkan terlibat dalam kasus penyuapan di City, karena itu ia akhirnya menjadi salah satu pemain yang dilelang bersama 17 pemain lainnya. Mangnall sangat cepat bergerak untuk mendapatkan tanda tangan pemain tersebut, bahkan sebelum lelang dimulai.</br>

	<br>Kedatangan pemain sayap tersebut terbukti menjadi inspirasi yang sangat besar, dimana Meredith berjasa dalam memberikan assist untuk pemain penyerang, Sandy Turnbull pada musim 1907/08. Musim dimana United meraih gelar juara liga untuk pertama kalinya. Sebagai pemenang, United akhirnya bisa bermain di Charity Shield untuk pertama kalinya. Mereka merebut gelar juara Charity Shield setelah mengalahkan pemenang Southern League, QPR dengan skor 4-0. Kemenangan tersebut tidak terlepas dari hat-trick yang dicetak oleh Jimmy Turnbull, nama julukan untuk Sandy Turnbull. Trofi ketiga yang menjadi koleksi United diraih mereka di ajang Piala FA, pada tahun 1909. Saat itu United mengalahkan Bristol City dengan skor 1-0 di babak final, dan gol kemenangan tersebut dipersembahkan oleh Sandy Turnbull.<br>
</body>
</html>